### ISSUE TITLE
Secret key string in config.py

### ISSUE THREAD

**Issue by webdog** [dashai/dashai#40]
:wave: @alyarctiq -- not sure if this is an issue or not, but I was checking dashai out, and noticed this hard string in the code, with the urandom generator commented out on the line above.

✨ 

https://github.com/dashai/dashai/blob/8f553bf3090e6e9736ed5e79aa32f35315f1d41f/app/config.py#L26

**Comment by alyarctiq** [comment]
Hey @webdog !
Yes current string is hardcoded, plan is to move to urandom which is just commented out as you noticed, but it presents a sessions handing issue when a new thread is spawned. Need to find a better way to handle that and randomize the key, so its on deck to resolve. I will use this issue to track.
